spring:
  profiles:
    active: online     # 本地环境
#    active: dev       # 环境
#    active: test      # 开发测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境

thymeleaf:
#    mode: LEGACYHTML5
    cache: false
    suffix: .html
    encoding: utf-8
    content-type: text/html
# health monitor
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@spring.boot.version@"

logging:
  config: classpath:logback-spring.xml
  level: INFO
#  level:
#      com:
#        bray:
#           service: DEBUG
#      org:
#        mybatis:
#           spring: DEBUG
##微信授权接口
#weixin4j:
#  id: wxfdd42e830e431893
#  secret: 902211bd94c8bc20e0801b669fbe9fe4
#  cache: FILE

weixin4j:
  id: wxbb4ab7ed932865b4
  secret: 85ff8381de984dba2e02067f5dbccb1d
  cache: FILE