spring:
  profiles:
    active: online     # 本地环境
#    active: dev       # 环境
#    active: test      # 开发测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境

thymeleaf:
#    mode: LEGACYHTML5
    cache: false
    suffix: .html
    encoding: utf-8
    content-type: text/html
# health monitor
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@spring.boot.version@"

logging:
  config: classpath:logback-spring.xml
  level: INFO

#微信授权接口
weixin4j:
  id: wx0681fdab518445d4
  secret: 851f53d92cc351f29f4e9486637e29a1
  cache: FILE