spring:
  profiles:
    active: dev     # 本地环境
#    active: dev       # 环境
#    active: test      # 开发测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境

# health monitor
info:
  app:
    name: "wechat-web"
    description: "Parent pom providing dependency and plugin management for applications
		built with Maven"
    version: "1.0-SNAPSHOT"
    spring-boot-version: "1.5.8.RELEASE"

logging:
  config: classpath:logback-spring.xml
  level: INFO

#微信授权接口
weixin4j:
  id: wxeb909a64d096f6ec
  secret: 19f303887c845a90f3cb5169525e5f04
  cache: FILE