spring:
  profiles:
    active: dev     # 本地环境
#    active: dev       # 环境
#    active: test      # 开发测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境

thymeleaf:
#    mode: LEGACYHTML5
    cache: false
    suffix: .html
    encoding: utf-8
    content-type: text/html
# health monitor
info:
  app:
    name: "wechat-web"
    description: "Parent pom providing dependency and plugin management for applications
		built with Maven"
    version: "1.0-SNAPSHOT"
    spring-boot-version: "1.5.8.RELEASE"

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com:
      bray: DEBUG
    org:
      mybatis:
         spring: DEBUG
##微信授权接口
#weixin4j:
#  id: wxfdd42e830e431893
#  secret: 902211bd94c8bc20e0801b669fbe9fe4
#  cache: FILE


weixin4j:
  id: wxbb4ab7ed932865b4
  secret: 85ff8381de984dba2e02067f5dbccb1d
  cache: FILE